#!/usr/bin/env bash

# Simple script that just runs all of the dcli apps
#
# Created by Mike Chambers
# https://www.mikechambers.com
#
# Released under an MIT License
#
# More info at:
# https://github.com/mikechambers/dcli/


echo "------------- RUNNING dclis--------------"
dclis --name mesh --platform xbox

echo "------------- RUNNING dclim--------------"
dclim

echo "------------- RUNNING dclic--------------"
dclic --name mesh#3230

echo "------------- RUNNING dclims--------------"
dclims --hash 3260604718

echo "------------- RUNNING dclia--------------"
dclia --name mesh#3230

echo "------------- RUNNING dclitime--------------"
dclitime

echo "------------- RUNNING dcliah --------------"
dcliah --name mesh#3230

echo "------------- RUNNING dcliad --------------"
dcliad --name mesh#3230
