#!/usr/bin/env bash

# Simple script that just runs all of the dcli apps
#
# Created by Mike Chambers
# https://www.mikechambers.com
#
# Released under an MIT License
#
# More info at:
# https://github.com/mikechambers/dcli/

# make sure you place the app in your PATH
dclis --id mesh --platform xbox
dclim --manifest-dir ~/tmp/
dclic --member-id 4611686018429783292 --platform xbox
dclims --manifest-path ~/tmp/manifest.sqlite3 --hash 3260604718
dclia --manifest-path ~/tmp/manifest.sqlite3 --member-id 4611686018429783292 --platform xbox
dclics --member-id 4611686018429783292 --platform xbox --mode all --character-id 2305843009264966985 --period week