#!/usr/bin/env bash

# Simple script that just runs all of the dcli apps
#
# Created by Mike Chambers
# https://www.mikechambers.com
#
# Released under an MIT License
#
# More info at:
# https://github.com/mikechambers/dcli/


echo "------------- RUNNING dclis--------------"
dclis --name mesh --platform xbox

echo "------------- RUNNING dclim--------------"
dclim

echo "------------- RUNNING dclic--------------"
dclic --member-id 4611686018429783292 --platform xbox

echo "------------- RUNNING dclims--------------"
dclims --hash 3260604718

echo "------------- RUNNING dclia--------------"
dclia --member-id 4611686018429783292 --platform xbox

echo "------------- RUNNING dclics--------------"
dclics --member-id 4611686018429783292 --platform xbox --character-id 2305843009264966985 

echo "------------- RUNNING dclitime--------------"
dclitime

echo "------------- RUNNING dcliah --------------"
dcliah --member-id 4611686018429783292 --platform xbox
