#!/usr/bin/env bash

# Monitors changes in activity status and send notification when it changes
#
# Works on: Mac OS X
#
# Created by Mike Chambers
# https://www.mikechambers.com
#
# Released under an MIT License
# More info at:
# https://github.com/mikechambers/dcli/

#https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -u

#pull variables from environment variables. Otherwise, you can
#just manually set them below

#you can get your member id and platform from dclim
MEMBER_ID=$MEMBER_ID
PLATFORM=$PLATFORM

##can get from dclim
MANIFEST_PATH=$MANIFEST_PATH

DEFAULT_CHECK_INTERVAL_SECONDS=15

echo "CTRL-C to end program"

OLD_ACTIVITY=""
while :
do
    CHECK_INTERVAL_SECONDS=$DEFAULT_CHECK_INTERVAL_SECONDS
    echo "Checking Status"
    ACTIVITY=$(dclia --manifest-path "$MANIFEST_PATH" --member-id "$MEMBER_ID" --platform "$PLATFORM")
    #note should do some error checking here in case command fails (can capture exit code)

    #we could have the command above output name / value pairs via --output-format tsv
    #and then filter based on type of activity (i.e. crucible, strikes, etc...)
    if [ "$OLD_ACTIVITY" != "$ACTIVITY" ]; then
        echo "Status has changed"
        echo "$ACTIVITY"
        #note, you could get this running on linux using notify-send command
	osascript -e "display notification \"${ACTIVITY}\" with title \"Destiny 2 Activity Changed\""
        OLD_ACTIVITY=$ACTIVITY

        CHECK_INTERVAL_SECONDS=60
    fi

    sleep $CHECK_INTERVAL_SECONDS
done
